# Generated by Django 6.0.6 on 2026-06-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_project_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='tracker_app.project'),
            preserve_default=False,
        ),
    ]
